### ISSUE TITLE
Grammar railroad diagram

### ISSUE THREAD

**Issue by mingodad** [mskelton/tree-sitter-mql5#11]
Using this page https://meimporta.eu/tree-sitter/json2ebnf.html we can get a navigable railroad diagram for tree-sitter grammars like this project.

See also https://github.com/tree-sitter/tree-sitter/issues/2268 .

Cheers !

**Comment by mskelton** [comment]
Why?

**Comment by mingodad** [comment]
To help document/debug/develop the grammar it's a visual/graph navigable way to see the grammar.

**Comment by mskelton** [comment]
I guess my recommendation would be to get more discussion in the upstream tree-sitter project before opening ~20 issues in downstream grammers assuming people want to do this. Comes across a little spammy at first TBH.

I don't see a compelling reason for it.

**Comment by mingodad** [comment]
I believe that the railroad diagram is a valuable tool for any grammar writer and I'm trying to spread it's usage among then.
I'm looking for grammars written in tree-sitter that have some serious effort and sending then the message.

**Comment by mskelton** [comment]
I guess I'm not convinced of the need given that people have been successfully building tree-sitter grammars for quite a while now. This is one of those things to let naturally work it's way into the ecosystem, rather than attempting to force it in.

Just my two cents.
